/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 注册出站回调并创建 Core。整个进程只调用一次。 */
export declare function start(onMessage: (...args: any[]) => any): void
/** 入站字节，转发给 Core 分发处理。 */
export declare function send(buf: Buffer): void
