/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 注册出站回调。整个进程只调用一次。 */
export declare function start(onMessage: (...args: any[]) => any): void
/** 入站字节。M0 阶段原样回声，验证通道通了。 */
export declare function send(buf: Buffer): void
