// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: hackerterm.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "hackerterm.v1";

export enum ErrorCode {
  ERROR_CODE_UNKNOWN = 0,
  ERROR_CODE_UNKNOWN_METHOD = 1,
  ERROR_CODE_INVALID_ARGUMENT = 2,
  ERROR_CODE_NOT_FOUND = 3,
  ERROR_CODE_CONNECT_FAILED = 6,
  ERROR_CODE_TIMEOUT = 8,
  ERROR_CODE_CANCELLED = 9,
  ERROR_CODE_INTERNAL = 11,
  UNRECOGNIZED = -1,
}

export enum Signal {
  SIGNAL_NONE = 0,
  SIGNAL_INT = 1,
  SIGNAL_TERM = 2,
  SIGNAL_KILL = 3,
  UNRECOGNIZED = -1,
}

export enum SessionState {
  SESSION_STATE_UNKNOWN = 0,
  SESSION_STATE_CONNECTED = 1,
  SESSION_STATE_CLOSED = 2,
  SESSION_STATE_FAILED = 3,
  UNRECOGNIZED = -1,
}

export interface Envelope {
  request?: Request | undefined;
  response?: Response | undefined;
  event?: Event | undefined;
}

export interface Request {
  id: number;
  method: string;
  payload: Uint8Array;
}

export interface Response {
  id: number;
  payload?: Uint8Array | undefined;
  error?: Error | undefined;
}

export interface Event {
  topic: string;
  payload: Uint8Array;
}

export interface Error {
  code: ErrorCode;
  key: string;
  params: { [key: string]: string };
  detail: string;
  retryable: boolean;
}

export interface Error_ParamsEntry {
  key: string;
  value: string;
}

export interface Hello {
  protocolMajor: number;
  protocolMinor: number;
  minSupportedMajor: number;
  implVersion: string;
  capabilities: string[];
}

export interface SessionOpenRequest {
  /** 空则用系统默认 */
  shell: string;
  cols: number;
  rows: number;
  cwd: string;
}

export interface SessionOpenResponse {
  sessionId: string;
}

export interface SessionResizeRequest {
  sessionId: string;
  cols: number;
  rows: number;
}

export interface SessionCloseRequest {
  sessionId: string;
}

export interface SessionAckRequest {
  sessionId: string;
  bytesConsumed: number;
}

export interface SessionSignalRequest {
  sessionId: string;
  signal: Signal;
}

export interface Empty {
}

export interface SessionStateEvent {
  sessionId: string;
  state: SessionState;
  error?: Error | undefined;
}

export interface SessionExitEvent {
  sessionId: string;
  exitCode: number;
}

/**
 * 流控停摆自愈事件（topic: session.flow_stalled）。
 *
 * 读线程因高水位暂停后，整整一个看门狗周期内未确认字节数一个字节都没降，判定
 * ack 通路已断，于是强制清零未确认窗口继续读（VS Code 的
 * TerminalProcess.clearUnacknowledgedChars() 等价物）。清零等于放弃背压，是
 * 降级不是修复，所以必须报出来——静默自愈会让真实的 ack 链路故障永远查不出来。
 *
 * 为什么不复用 SessionStateEvent：那个消息的语义是"会话状态机变到了哪一档"
 * （Connected/Closed/Failed），而这里会话既没关也没失败，只是流控记账被放弃了；
 * 塞进 Failed 会让渲染层以为会话已经死了。
 */
export interface SessionFlowStalledEvent {
  sessionId: string;
  /** 被强制丢弃的未确认字节数 */
  unacknowledgedBytes: number;
  /** 判定停摆用的等待时长 */
  stalledMs: number;
}

/**
 * core.stats：进程级诊断快照。
 *
 * 存在的理由是"读线程死没死"在真机上完全不可见。读线程停止的正常路径已经会经
 * session.state 报出来，但**panic 会直接跳过那条上报**，而"数据永远不再来"正是
 * 本项目反复出现的症状。所以需要一个不依赖任何事件、随时可查的计数——事件只能
 * 证明发生过什么，证明不了此刻还剩几个线程活着。
 */
export interface CoreStatsRequest {
}

export interface CoreStatsResponse {
  liveReadThreads: number;
}

function createBaseEnvelope(): Envelope {
  return { request: undefined, response: undefined, event: undefined };
}

export const Envelope: MessageFns<Envelope> = {
  encode(message: Envelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request !== undefined) {
      Request.encode(message.request, writer.uint32(10).fork()).join();
    }
    if (message.response !== undefined) {
      Response.encode(message.response, writer.uint32(18).fork()).join();
    }
    if (message.event !== undefined) {
      Event.encode(message.event, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.request = Request.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.response = Response.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.event = Event.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRequest(): Request {
  return { id: 0, method: "", payload: new Uint8Array(0) };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.method !== "") {
      writer.uint32(18).string(message.method);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseResponse(): Response {
  return { id: 0, payload: undefined, error: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.payload !== undefined) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEvent(): Event {
  return { topic: "", payload: new Uint8Array(0) };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.topic !== "") {
      writer.uint32(10).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseError(): Error {
  return { code: 0, key: "", params: {}, detail: "", retryable: false };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    globalThis.Object.entries(message.params).forEach(([key, value]: [string, string]) => {
      Error_ParamsEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.detail !== "") {
      writer.uint32(34).string(message.detail);
    }
    if (message.retryable !== false) {
      writer.uint32(40).bool(message.retryable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Error_ParamsEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.params[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.detail = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retryable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseError_ParamsEntry(): Error_ParamsEntry {
  return { key: "", value: "" };
}

export const Error_ParamsEntry: MessageFns<Error_ParamsEntry> = {
  encode(message: Error_ParamsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error_ParamsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError_ParamsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHello(): Hello {
  return { protocolMajor: 0, protocolMinor: 0, minSupportedMajor: 0, implVersion: "", capabilities: [] };
}

export const Hello: MessageFns<Hello> = {
  encode(message: Hello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocolMajor !== 0) {
      writer.uint32(8).uint32(message.protocolMajor);
    }
    if (message.protocolMinor !== 0) {
      writer.uint32(16).uint32(message.protocolMinor);
    }
    if (message.minSupportedMajor !== 0) {
      writer.uint32(24).uint32(message.minSupportedMajor);
    }
    if (message.implVersion !== "") {
      writer.uint32(34).string(message.implVersion);
    }
    for (const v of message.capabilities) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHello();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.protocolMajor = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.protocolMinor = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minSupportedMajor = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.implVersion = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionOpenRequest(): SessionOpenRequest {
  return { shell: "", cols: 0, rows: 0, cwd: "" };
}

export const SessionOpenRequest: MessageFns<SessionOpenRequest> = {
  encode(message: SessionOpenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shell !== "") {
      writer.uint32(10).string(message.shell);
    }
    if (message.cols !== 0) {
      writer.uint32(16).uint32(message.cols);
    }
    if (message.rows !== 0) {
      writer.uint32(24).uint32(message.rows);
    }
    if (message.cwd !== "") {
      writer.uint32(34).string(message.cwd);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionOpenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionOpenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shell = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cols = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rows = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cwd = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionOpenResponse(): SessionOpenResponse {
  return { sessionId: "" };
}

export const SessionOpenResponse: MessageFns<SessionOpenResponse> = {
  encode(message: SessionOpenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionOpenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionOpenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionResizeRequest(): SessionResizeRequest {
  return { sessionId: "", cols: 0, rows: 0 };
}

export const SessionResizeRequest: MessageFns<SessionResizeRequest> = {
  encode(message: SessionResizeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.cols !== 0) {
      writer.uint32(16).uint32(message.cols);
    }
    if (message.rows !== 0) {
      writer.uint32(24).uint32(message.rows);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionResizeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionResizeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cols = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rows = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionCloseRequest(): SessionCloseRequest {
  return { sessionId: "" };
}

export const SessionCloseRequest: MessageFns<SessionCloseRequest> = {
  encode(message: SessionCloseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionCloseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionCloseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionAckRequest(): SessionAckRequest {
  return { sessionId: "", bytesConsumed: 0 };
}

export const SessionAckRequest: MessageFns<SessionAckRequest> = {
  encode(message: SessionAckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.bytesConsumed !== 0) {
      writer.uint32(16).uint64(message.bytesConsumed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionAckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionAckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bytesConsumed = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionSignalRequest(): SessionSignalRequest {
  return { sessionId: "", signal: 0 };
}

export const SessionSignalRequest: MessageFns<SessionSignalRequest> = {
  encode(message: SessionSignalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.signal !== 0) {
      writer.uint32(16).int32(message.signal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionSignalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionSignalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.signal = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionStateEvent(): SessionStateEvent {
  return { sessionId: "", state: 0, error: undefined };
}

export const SessionStateEvent: MessageFns<SessionStateEvent> = {
  encode(message: SessionStateEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.state !== 0) {
      writer.uint32(16).int32(message.state);
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionStateEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionStateEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionExitEvent(): SessionExitEvent {
  return { sessionId: "", exitCode: 0 };
}

export const SessionExitEvent: MessageFns<SessionExitEvent> = {
  encode(message: SessionExitEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.exitCode !== 0) {
      writer.uint32(16).int32(message.exitCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionExitEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionExitEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.exitCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSessionFlowStalledEvent(): SessionFlowStalledEvent {
  return { sessionId: "", unacknowledgedBytes: 0, stalledMs: 0 };
}

export const SessionFlowStalledEvent: MessageFns<SessionFlowStalledEvent> = {
  encode(message: SessionFlowStalledEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.unacknowledgedBytes !== 0) {
      writer.uint32(16).uint64(message.unacknowledgedBytes);
    }
    if (message.stalledMs !== 0) {
      writer.uint32(24).uint64(message.stalledMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionFlowStalledEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionFlowStalledEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.unacknowledgedBytes = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.stalledMs = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCoreStatsRequest(): CoreStatsRequest {
  return {};
}

export const CoreStatsRequest: MessageFns<CoreStatsRequest> = {
  encode(_: CoreStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCoreStatsResponse(): CoreStatsResponse {
  return { liveReadThreads: 0 };
}

export const CoreStatsResponse: MessageFns<CoreStatsResponse> = {
  encode(message: CoreStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.liveReadThreads !== 0) {
      writer.uint32(8).uint32(message.liveReadThreads);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CoreStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoreStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.liveReadThreads = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
